INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CONVOLUTION_CODES Convolution_Codes)

FIND_PATH(
    CONVOLUTION_CODES_INCLUDE_DIRS
    NAMES Convolution_Codes/api.h
    HINTS $ENV{CONVOLUTION_CODES_DIR}/include
        ${PC_CONVOLUTION_CODES_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CONVOLUTION_CODES_LIBRARIES
    NAMES gnuradio-Convolution_Codes
    HINTS $ENV{CONVOLUTION_CODES_DIR}/lib
        ${PC_CONVOLUTION_CODES_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CONVOLUTION_CODES DEFAULT_MSG CONVOLUTION_CODES_LIBRARIES CONVOLUTION_CODES_INCLUDE_DIRS)
MARK_AS_ADVANCED(CONVOLUTION_CODES_LIBRARIES CONVOLUTION_CODES_INCLUDE_DIRS)

